In [1]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as dates
from matplotlib.ticker import AutoMinorLocator
import datetime as dt
import numpy as np
import gc

In [2]:
from pathlib import Path
import pandas as pd
root = Path('dataframe', 'daily_avg_over_yrs')
df = pd.read_csv(root / 'action.csv')
del df['Unnamed: 0']
df.head()

  mth_day     Action  Action_norm
0   01-01        NaN          NaN
1   01-02  18.100457    -1.290930
2   01-03  19.838887    -0.492246
3   01-04  18.462805    -1.124457
4   01-05  17.146156    -1.729362

In [ ]:
#df['action_ravg'] = df['action_norm'].rolling(window=6,center=True).mean()

In [ ]:
df.loc[df['action_ravg'].idxmax()]['mth_day']
df.loc[df['action_ravg'].idxmax()]['action_ravg']

In [ ]:
df.plot(x='mth_day',y='action_ravg',figsize = (15,8))

In [27]:
tag_array.index("crime")

54

In [40]:
df2 = pd.DataFrame(columns=['tag','date','ravg_value'])
df1 = pd.read_csv("tags.csv")
n = 170
tag_array = df1['tag'].value_counts()[:n].index.tolist()
print(tag_array)
df = pd.read_csv("pg_view_1.csv") 
from pathlib import Path
import pandas as pd
root = Path('dataframe', 'daily_avg_over_yrs')
i = 0
for tag in tag_array:
    tagn = tag+'.csv'
    df = pd.read_csv(root / tagn)
    df.columns = map(str.lower, df.columns)
    date = df.loc[df[tag.lower()+'_ravg'].idxmax()]['mth_day']
    ravg_value = df.loc[df[tag.lower()+'_ravg'].idxmax()][tag.lower()+'_ravg']
    df2.loc[i] = [tag.lower(),date,ravg_value]
    i +=1

['sci-fi', 'atmospheric', 'action', 'comedy', 'surreal', 'based on a book', 'funny', 'twist ending', 'visually appealing', 'dystopia', 'BD-R', 'dark comedy', 'thought-provoking', 'romance', 'woman director', 'stylized', 'quirky', 'psychology', 'fantasy', 'classic', 'violence', 'murder', 'time travel', 'social commentary', 'revenge', 'thriller', 'space', 'cinematography', 'superhero', 'adventure', 'dark', 'aliens', 'suspense', 'disturbing', 'animation', 'coming of age', 'great soundtrack', 'horror', 'drama', 'Criterion', 'drugs', 'music', 'musical', 'psychological', 'cult film', 'friendship', 'true story', 'based on a true story', 'post-apocalyptic', 'predictable', 'black comedy', 'satire', 'independent film', 'serial killer', 'Nudity (Topless)', 'bittersweet', 'crime', 'family', 'mindfuck', 'dreamlike', 'mystery', 'high school', 'war', 'imdb top 250', 'love', 'artificial intelligence', 'boring', 'World War II', 'mental illness', 'politics', 'tense', 'sequel', 'magic', 'great acting', 'inspirational', 'future', 'violent', 'alternate reality', 'witty', 'nudity (topless)', 'comic book', 'biography', 'religion', 'martial arts', 'anime', 'nonlinear', 'Disney', 'CLV', 'police', 'philosophy', 'emotional', 'parody', 'black and white', 'philosophical', 'Quentin Tarantino', 'survival', 'rape', 'beautiful', 'zombies', 'science fiction', 'gay', 'soundtrack', 'remake', 'history', 'slow', 'plot twist', 'sex', 'based on novel or book', 'multiple storylines', 'humorous', 'documentary', 'robots', 'Betamax', 'gore', 'prison', 'Marvel', 'espionage', 'historical', 'short', 'Oscar (Best Picture)', 'franchise', 'organized crime', 'visually stunning', 'original', 'intelligent', 'corruption', 'touching', 'cyberpunk', 'hilarious', 'dark humor', 'adapted from:book', 'racism', 'futuristic', 'supernatural', 'Leonardo DiCaprio', 'fairy tale', 'heist', 'loneliness', 'suicide', 'DVD-Video', 'military', 'stupid', 'weird', 'Johnny Depp', 'dialogue', 'conspiracy', 'overrated', 'Brad Pitt', 'kidnapping', 'road trip', 'sexuality', 'lesbian', 'assassin', 'New York City', 'small town', 'Oscar Nominee: Best Picture', 'intense', 'ensemble cast', 'clever', 'Tom Hanks', 'Japan', 'strong female lead', 'film noir', 'Pixar', 'creepy', 'stand-up comedy', 'spy', 'Bruce Willis', 'Action', 'death']

In [47]:
# df2 = df2.sort_values('ravg_value')
df2.tail(50)

,tag,date,ravg_value
120,franchise,06-11,1.58982
121,organized crime,11-06,1.28261
122,visually stunning,06-20,1.63175
123,original,09-22,1.41238
124,intelligent,05-19,1.43701
125,corruption,11-08,1.35739
126,touching,06-14,1.35051
127,cyberpunk,06-16,1.85899
128,hilarious,06-14,1.78286
129,dark humor,05-19,1.6577
130,adapted from:book,06-14,1.55148
131,racism,05-20,2.07639
132,futuristic,05-27,1.69055
133,supernatural,12-01,1.52111
134,leonardo dicaprio,"43 02-13 43 02-13 Name: mth_day, dtype: ...",leonardo dicaprio_ravg leonardo dicaprio_...
135,fairy tale,11-29,1.41107
136,heist,06-27,1.39776
137,loneliness,05-21,1.20183
138,suicide,06-15,1.27324
139,dvd-video,"4 01-05 4 01-05 Name: mth_day, dtype: ob...",dvd-video_ravg dvd-video_ravg 4 ...
140,military,06-12,1.43385
141,stupid,05-19,1.6279
142,weird,06-20,1.73432
143,johnny depp,"215 08-03 215 08-03 Name: mth_day, dtype...",johnny depp_ravg johnny depp_ravg 215 ...
144,dialogue,06-14,1.3392
145,conspiracy,07-12,1.19516
146,overrated,05-19,1.73067
147,brad pitt,"152 06-01 152 06-01 Name: mth_day, dtype...",brad pitt_ravg brad pitt_ravg 152 ...
148,kidnapping,05-27,1.60195
149,road trip,06-17,1.47211
150,sexuality,05-19,1.85737
151,lesbian,08-24,1.92198
152,assassin,05-20,1.48457
153,new york city,"160 06-09 160 06-09 Name: mth_day, dtype...",new york city_ravg new york city_ravg 16...
154,small town,06-10,1.78134
155,oscar nominee: best picture,"143 05-23 143 05-23 Name: mth_day, dtype...",oscar nominee: best picture_ravg oscar n...
156,intense,05-19,1.50383
157,ensemble cast,05-19,1.49304
158,clever,05-23,1.65432
159,tom hanks,"126 05-06 126 05-06 Name: mth_day, dtype...",tom hanks_ravg tom hanks_ravg 126 ...
160,japan,"133 05-13 133 05-13 Name: mth_day, dtype...",japan_ravg japan_ravg 133 1.491689 ...
161,strong female lead,06-13,1.27772
162,film noir,06-20,1.52857
163,pixar,"126 05-06 126 05-06 Name: mth_day, dtype...",pixar_ravg pixar_ravg 126 2.50633 ...
164,creepy,06-15,1.62109
165,stand-up comedy,04-24,2.36519
166,spy,05-30,1.34373
167,bruce willis,"141 05-21 141 05-21 Name: mth_day, dtype...",bruce willis_ravg bruce willis_ravg 141 ...
168,action,"176 25-Jun 176 25-Jun Name: mth_day, dty...",action_ravg action_ravg 176 1.741709...
169,death,06-15,1.85282

In [31]:
df2 = pd.DataFrame(columns=['tag','date','ravg_value'])
df1 = pd.read_csv("tags.csv")
n = 170
tag_array = df1['tag'].value_counts()[:n].index.tolist()
from pathlib import Path
import pandas as pd
root = Path('dataframe', 'daily_avg_over_yrs')
for tag in tag_array:
    tagn = tag+'.csv'
    df = pd.read_csv(root / tagn)
    df.columns = map(str.lower, df.columns)
    df[tag.lower()+'_ravg'] = df[tag.lower()+'_norm'].rolling(window=6,center=True).mean()
#     fig = df.plot(x='mth_day',y= tag+'_ravg',figsize = (15,8))
#     fig.figure.savefig('graphs/daily_avg_over_yrs/rolling_avg/'+ tag+'_ravg.pdf')
    df.to_csv('dataframe/daily_avg_over_yrs/'+ tag +'.csv')